apiVersion: v1
kind: Pod
metadata:
  name: worker-app-pod
  labels:
    name: worker-main-pod
    app: sample-voting-app

spec:
  containers:
  - name: worker-app
    image: dockersamples/examplevotingapp_worker
    ports: